#!/bin/bash
set -e
PROGNAME=$(basename "$0")
PROGNAME=${PROGNAME%-sub}
CMDNAME=${PROGNAME//-/ }
SCRIPTS_TOPDIR=$(cd $(dirname "$0") && cd .. && pwd)
source "${SCRIPTS_TOPDIR}/lib/revdb-functions.include.sh"
source "${SCRIPTS_TOPDIR}/conf/config.sh.conf"

show_usage()
{
    cat <<__DOC__
Usage: ${CMDNAME} PROJECT-ID REVISION-DESCRIPTION...

__DOC__
}

PROJECTID_ORIG="$1"
if [ -z "${PROJECTID_ORIG}" ] ; then
    show_error    "ERROR: ${PROGNAME}: must provide project ID"
    show_usage >&2
    exit 1
fi

PROJECTID=$(echo -n "$PROJECTID_ORIG" | revdb_read_exactly_one_word)
if [ "${PROJECTID_ORIG}" != "${PROJECTID}" ] ; then
    show_error    "ERROR: ${PROGNAME}: must provide valid project ID"
    show_usage >&2
    exit 1
fi

shift
DESCRIPTION="$@"

if [ -z "${DESCRIPTION}" ] ; then
    show_error    "ERROR: ${PROGNAME}: must provide description for next revision"
    show_usage >&2
    exit 1
fi

CURR_DATE=$(TZ=UTC LANG=C date '+%Y-%m-%d %H:%M:%S')
DESCRIPTION_FILTERED=$(echo -n "${DESCRIPTION}" | revdb_read_exactly_one_line)

SUBDIR=$(revdb_get_subdir "${PROJECTID}")
if [ ! -d "${DBDIR}/${SUBDIR}" ] ; then
    show_error    "ERROR: ${PROGNAME}: no such project ${PROJECTID}"
    exit 1
fi

NEXT_NUMBER=$(cd ${DBDIR}/${SUBDIR} && revdb_number_get_and_incr)
if [ -z "${NEXT_NUMBER}" ] ; then
    show_error    "ERROR: ${PROGNAME}: no next revision number for project ${PROJECTID}"
    exit 1
fi

cp --archive "${DBDIR}/${SUBDIR}/revisions.txt" "${DBDIR}/${SUBDIR}/revisions.txt.old"

{
cat "${DBDIR}/${SUBDIR}/revisions.txt"
echo "|${NEXT_NUMBER}|${CURR_DATE}|${DESCRIPTION_FILTERED}|"
} >"${DBDIR}/${SUBDIR}/revisions.txt.new"

mv "${DBDIR}/${SUBDIR}/revisions.txt.new" "${DBDIR}/${SUBDIR}/revisions.txt"


echo "${NEXT_NUMBER}"

exit 0
